Avoid catch-all rescue and using exceptions for control-flow
The catch-all rescue in lib/devise_capturable/strategy.rb:63 was hiding
the helpful error message in the previous commit message:

    undefined method `capturable_server' for Devise:Module

Rescuing "Exception" seems like a dubious practice in general: helpful
messages might not get propagated when they should, and many Exceptions
that do not inherit from StandardError cannot be meaningfully handled
anyway.

There is only one example that relies on this behavior in the spec: when
saving a user fails (by raising Exception).

Instead of using this exception for control-flow, just check the result
of user.save (no bang) and call "fail!" right there if needed.  Avoid
the top-level rescue all together rather than weakening it to something
like StandardError because a Devise's prominent warden strategy also has
no top-level rescue.